// Focus management for config screen

#[derive(Default, Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConfigFocus {
    // Profile management
    #[default]
    ProfileList,
    SaveButton,
    DeleteButton,

    // General settings
    OutputDirectory,
    FilenamePattern,
    ContainerDropdown,
    OverwriteCheckbox,

    // Video output constraints
    FpsDropdown,
    ResolutionDropdown,

    // Rate control
    RateControlMode,
    CrfSlider,
    VideoTargetBitrateInput,
    VideoMinBitrateInput,
    VideoMaxBitrateInput,
    VideoBufsizeInput,
    UndershootPctInput,
    OvershootPctInput,

    // Auto-VMAF
    AutoVmafCheckbox,
    AutoVmafTargetInput,
    AutoVmafStepInput,
    AutoVmafMaxAttemptsInput,

    // Speed & quality
    QualityMode,
    CpuUsedSlider,
    CpuUsedPass1Slider,
    CpuUsedPass2Slider,
    TwoPassCheckbox,

    // Hardware encoding (Intel Arc VAAPI)
    HardwareEncodingCheckbox,
    QsvGlobalQualitySlider,
    VaapiCompressionLevelSlider,
    VaapiBFramesInput,
    VaapiLoopFilterLevelInput,
    VaapiLoopFilterSharpnessInput,
    HwDenoiseInput,
    HwDetailInput,
    Vp9QsvPresetSlider,
    Vp9QsvLookaheadCheckbox,
    Vp9QsvLookaheadDepthInput,

    // Video codec selector (VP9/AV1)
    VideoCodecDropdown,

    // VP9 settings
    ProfileDropdown,
    PixFmtDropdown,

    // AV1 software settings (libsvtav1)
    Av1PresetSlider,
    Av1TuneDropdown,
    Av1FilmGrainSlider,
    Av1FilmGrainDenoiseCheckbox,
    Av1EnableOverlaysCheckbox,
    Av1ScdCheckbox,
    Av1ScmDropdown,
    Av1EnableTfCheckbox,

    // AV1 hardware settings
    Av1HwPresetSlider,
    Av1HwCqSlider,
    Av1HwLookaheadInput,
    Av1HwTileColsInput,
    Av1HwTileRowsInput,

    // Parallelism
    RowMtCheckbox,
    TileColumnsSlider,
    TileRowsSlider,
    ThreadsInput,
    MaxWorkersInput,
    FrameParallelCheckbox,

    // GOP & keyframes
    GopLengthInput,
    KeyintMinInput,
    FixedGopCheckbox,
    LagInFramesSlider,
    AutoAltRefCheckbox,

    // Adaptive quantization
    AqModeDropdown,

    // Alt-ref denoising
    ArnrMaxFramesSlider,
    ArnrStrengthSlider,
    ArnrTypeDropdown,

    // Advanced tuning
    TuneContentDropdown,
    EnableTplCheckbox,
    SharpnessSlider,
    NoiseSensitivitySlider,
    StaticThreshInput,
    MaxIntraRateInput,

    // Color / HDR
    ColorSpacePresetDropdown,

    // Audio - multi-track support
    AudioPrimaryCodec,
    AudioPrimaryBitrate,
    AudioPrimaryDownmix,
    AudioAc3Checkbox,
    AudioAc3Bitrate,
    AudioStereoCheckbox,
    AudioStereoCodec,
    AudioStereoBitrate,

    // Additional FFmpeg arguments
    AdditionalArgsInput,
}

impl ConfigFocus {
    pub fn next(&self) -> Self {
        match self {
            Self::ProfileList => Self::SaveButton,
            Self::SaveButton => Self::DeleteButton,
            Self::DeleteButton => Self::OutputDirectory,
            Self::OutputDirectory => Self::FilenamePattern,
            Self::FilenamePattern => Self::ContainerDropdown,
            Self::ContainerDropdown => Self::OverwriteCheckbox,
            Self::OverwriteCheckbox => Self::FpsDropdown,
            Self::FpsDropdown => Self::ResolutionDropdown,
            Self::ResolutionDropdown => Self::RateControlMode,
            Self::RateControlMode => Self::CrfSlider,
            Self::CrfSlider => Self::VideoTargetBitrateInput,
            Self::VideoTargetBitrateInput => Self::VideoMinBitrateInput,
            Self::VideoMinBitrateInput => Self::VideoMaxBitrateInput,
            Self::VideoMaxBitrateInput => Self::VideoBufsizeInput,
            Self::VideoBufsizeInput => Self::UndershootPctInput,
            Self::UndershootPctInput => Self::OvershootPctInput,
            Self::OvershootPctInput => Self::AutoVmafCheckbox,
            Self::AutoVmafCheckbox => Self::AutoVmafTargetInput,
            Self::AutoVmafTargetInput => Self::AutoVmafStepInput,
            Self::AutoVmafStepInput => Self::AutoVmafMaxAttemptsInput,
            Self::AutoVmafMaxAttemptsInput => Self::QualityMode,
            Self::QualityMode => Self::CpuUsedSlider,
            Self::CpuUsedSlider => Self::CpuUsedPass1Slider,
            Self::CpuUsedPass1Slider => Self::CpuUsedPass2Slider,
            Self::CpuUsedPass2Slider => Self::TwoPassCheckbox,
            Self::TwoPassCheckbox => Self::HardwareEncodingCheckbox,
            Self::HardwareEncodingCheckbox => Self::QsvGlobalQualitySlider,
            Self::QsvGlobalQualitySlider => Self::VaapiCompressionLevelSlider,
            Self::VaapiCompressionLevelSlider => Self::VaapiBFramesInput,
            Self::VaapiBFramesInput => Self::VaapiLoopFilterLevelInput,
            Self::VaapiLoopFilterLevelInput => Self::VaapiLoopFilterSharpnessInput,
            Self::VaapiLoopFilterSharpnessInput => Self::HwDenoiseInput,
            Self::HwDenoiseInput => Self::HwDetailInput,
            Self::HwDetailInput => Self::Vp9QsvPresetSlider,
            Self::Vp9QsvPresetSlider => Self::Vp9QsvLookaheadCheckbox,
            Self::Vp9QsvLookaheadCheckbox => Self::Vp9QsvLookaheadDepthInput,
            Self::Vp9QsvLookaheadDepthInput => Self::VideoCodecDropdown,
            Self::VideoCodecDropdown => Self::ProfileDropdown,
            Self::ProfileDropdown => Self::PixFmtDropdown,
            Self::PixFmtDropdown => Self::Av1PresetSlider,
            Self::Av1PresetSlider => Self::Av1TuneDropdown,
            Self::Av1TuneDropdown => Self::Av1FilmGrainSlider,
            Self::Av1FilmGrainSlider => Self::Av1FilmGrainDenoiseCheckbox,
            Self::Av1FilmGrainDenoiseCheckbox => Self::Av1EnableOverlaysCheckbox,
            Self::Av1EnableOverlaysCheckbox => Self::Av1ScdCheckbox,
            Self::Av1ScdCheckbox => Self::Av1ScmDropdown,
            Self::Av1ScmDropdown => Self::Av1EnableTfCheckbox,
            Self::Av1EnableTfCheckbox => Self::Av1HwPresetSlider,
            Self::Av1HwPresetSlider => Self::Av1HwCqSlider,
            Self::Av1HwCqSlider => Self::Av1HwLookaheadInput,
            Self::Av1HwLookaheadInput => Self::Av1HwTileColsInput,
            Self::Av1HwTileColsInput => Self::Av1HwTileRowsInput,
            Self::Av1HwTileRowsInput => Self::RowMtCheckbox,
            Self::RowMtCheckbox => Self::TileColumnsSlider,
            Self::TileColumnsSlider => Self::TileRowsSlider,
            Self::TileRowsSlider => Self::ThreadsInput,
            Self::ThreadsInput => Self::MaxWorkersInput,
            Self::MaxWorkersInput => Self::FrameParallelCheckbox,
            Self::FrameParallelCheckbox => Self::GopLengthInput,
            Self::GopLengthInput => Self::KeyintMinInput,
            Self::KeyintMinInput => Self::FixedGopCheckbox,
            Self::FixedGopCheckbox => Self::LagInFramesSlider,
            Self::LagInFramesSlider => Self::AutoAltRefCheckbox,
            Self::AutoAltRefCheckbox => Self::AqModeDropdown,
            Self::AqModeDropdown => Self::ArnrMaxFramesSlider,
            Self::ArnrMaxFramesSlider => Self::ArnrStrengthSlider,
            Self::ArnrStrengthSlider => Self::ArnrTypeDropdown,
            Self::ArnrTypeDropdown => Self::TuneContentDropdown,
            Self::TuneContentDropdown => Self::EnableTplCheckbox,
            Self::EnableTplCheckbox => Self::SharpnessSlider,
            Self::SharpnessSlider => Self::NoiseSensitivitySlider,
            Self::NoiseSensitivitySlider => Self::StaticThreshInput,
            Self::StaticThreshInput => Self::MaxIntraRateInput,
            Self::MaxIntraRateInput => Self::ColorSpacePresetDropdown,
            Self::ColorSpacePresetDropdown => Self::AudioPrimaryCodec,
            Self::AudioPrimaryCodec => Self::AudioPrimaryBitrate,
            Self::AudioPrimaryBitrate => Self::AudioPrimaryDownmix,
            Self::AudioPrimaryDownmix => Self::AudioAc3Checkbox,
            Self::AudioAc3Checkbox => Self::AudioAc3Bitrate,
            Self::AudioAc3Bitrate => Self::AudioStereoCheckbox,
            Self::AudioStereoCheckbox => Self::AudioStereoCodec,
            Self::AudioStereoCodec => Self::AudioStereoBitrate,
            Self::AudioStereoBitrate => Self::AdditionalArgsInput,
            Self::AdditionalArgsInput => Self::ProfileList, // Wrap around
        }
    }

    pub fn previous(&self) -> Self {
        match self {
            Self::ProfileList => Self::AdditionalArgsInput, // Wrap around
            Self::SaveButton => Self::ProfileList,
            Self::DeleteButton => Self::SaveButton,
            Self::OutputDirectory => Self::DeleteButton,
            Self::FilenamePattern => Self::OutputDirectory,
            Self::ContainerDropdown => Self::FilenamePattern,
            Self::OverwriteCheckbox => Self::ContainerDropdown,
            Self::FpsDropdown => Self::OverwriteCheckbox,
            Self::ResolutionDropdown => Self::FpsDropdown,
            Self::RateControlMode => Self::ResolutionDropdown,
            Self::CrfSlider => Self::RateControlMode,
            Self::VideoTargetBitrateInput => Self::CrfSlider,
            Self::VideoMinBitrateInput => Self::VideoTargetBitrateInput,
            Self::VideoMaxBitrateInput => Self::VideoMinBitrateInput,
            Self::VideoBufsizeInput => Self::VideoMaxBitrateInput,
            Self::UndershootPctInput => Self::VideoBufsizeInput,
            Self::OvershootPctInput => Self::UndershootPctInput,
            Self::AutoVmafCheckbox => Self::OvershootPctInput,
            Self::AutoVmafTargetInput => Self::AutoVmafCheckbox,
            Self::AutoVmafStepInput => Self::AutoVmafTargetInput,
            Self::AutoVmafMaxAttemptsInput => Self::AutoVmafStepInput,
            Self::QualityMode => Self::AutoVmafMaxAttemptsInput,
            Self::CpuUsedSlider => Self::QualityMode,
            Self::CpuUsedPass1Slider => Self::CpuUsedSlider,
            Self::CpuUsedPass2Slider => Self::CpuUsedPass1Slider,
            Self::TwoPassCheckbox => Self::CpuUsedPass2Slider,
            Self::HardwareEncodingCheckbox => Self::TwoPassCheckbox,
            Self::QsvGlobalQualitySlider => Self::HardwareEncodingCheckbox,
            Self::VaapiCompressionLevelSlider => Self::QsvGlobalQualitySlider,
            Self::VaapiBFramesInput => Self::VaapiCompressionLevelSlider,
            Self::VaapiLoopFilterLevelInput => Self::VaapiBFramesInput,
            Self::VaapiLoopFilterSharpnessInput => Self::VaapiLoopFilterLevelInput,
            Self::HwDenoiseInput => Self::VaapiLoopFilterSharpnessInput,
            Self::HwDetailInput => Self::HwDenoiseInput,
            Self::Vp9QsvPresetSlider => Self::HwDetailInput,
            Self::Vp9QsvLookaheadCheckbox => Self::Vp9QsvPresetSlider,
            Self::Vp9QsvLookaheadDepthInput => Self::Vp9QsvLookaheadCheckbox,
            Self::VideoCodecDropdown => Self::Vp9QsvLookaheadDepthInput,
            Self::ProfileDropdown => Self::VideoCodecDropdown,
            Self::PixFmtDropdown => Self::ProfileDropdown,
            Self::Av1PresetSlider => Self::PixFmtDropdown,
            Self::Av1TuneDropdown => Self::Av1PresetSlider,
            Self::Av1FilmGrainSlider => Self::Av1TuneDropdown,
            Self::Av1FilmGrainDenoiseCheckbox => Self::Av1FilmGrainSlider,
            Self::Av1EnableOverlaysCheckbox => Self::Av1FilmGrainDenoiseCheckbox,
            Self::Av1ScdCheckbox => Self::Av1EnableOverlaysCheckbox,
            Self::Av1ScmDropdown => Self::Av1ScdCheckbox,
            Self::Av1EnableTfCheckbox => Self::Av1ScmDropdown,
            Self::Av1HwPresetSlider => Self::Av1EnableTfCheckbox,
            Self::Av1HwCqSlider => Self::Av1HwPresetSlider,
            Self::Av1HwLookaheadInput => Self::Av1HwCqSlider,
            Self::Av1HwTileColsInput => Self::Av1HwLookaheadInput,
            Self::Av1HwTileRowsInput => Self::Av1HwTileColsInput,
            Self::RowMtCheckbox => Self::Av1HwTileRowsInput,
            Self::TileColumnsSlider => Self::RowMtCheckbox,
            Self::TileRowsSlider => Self::TileColumnsSlider,
            Self::ThreadsInput => Self::TileRowsSlider,
            Self::MaxWorkersInput => Self::ThreadsInput,
            Self::FrameParallelCheckbox => Self::MaxWorkersInput,
            Self::GopLengthInput => Self::FrameParallelCheckbox,
            Self::KeyintMinInput => Self::GopLengthInput,
            Self::FixedGopCheckbox => Self::KeyintMinInput,
            Self::LagInFramesSlider => Self::FixedGopCheckbox,
            Self::AutoAltRefCheckbox => Self::LagInFramesSlider,
            Self::AqModeDropdown => Self::AutoAltRefCheckbox,
            Self::ArnrMaxFramesSlider => Self::AqModeDropdown,
            Self::ArnrStrengthSlider => Self::ArnrMaxFramesSlider,
            Self::ArnrTypeDropdown => Self::ArnrStrengthSlider,
            Self::TuneContentDropdown => Self::ArnrTypeDropdown,
            Self::EnableTplCheckbox => Self::TuneContentDropdown,
            Self::SharpnessSlider => Self::EnableTplCheckbox,
            Self::NoiseSensitivitySlider => Self::SharpnessSlider,
            Self::StaticThreshInput => Self::NoiseSensitivitySlider,
            Self::MaxIntraRateInput => Self::StaticThreshInput,
            Self::ColorSpacePresetDropdown => Self::MaxIntraRateInput,
            Self::AudioPrimaryCodec => Self::ColorSpacePresetDropdown,
            Self::AudioPrimaryBitrate => Self::AudioPrimaryCodec,
            Self::AudioPrimaryDownmix => Self::AudioPrimaryBitrate,
            Self::AudioAc3Checkbox => Self::AudioPrimaryDownmix,
            Self::AudioAc3Bitrate => Self::AudioAc3Checkbox,
            Self::AudioStereoCheckbox => Self::AudioAc3Bitrate,
            Self::AudioStereoCodec => Self::AudioStereoCheckbox,
            Self::AudioStereoBitrate => Self::AudioStereoCodec,
            Self::AdditionalArgsInput => Self::AudioStereoBitrate,
        }
    }
}
