//! Built-in encoding profile definitions.
//!
//! This module contains all the hardcoded profile presets that ship with ffdash.
//! Profiles are organized into categories:
//! - Base codec profiles (av1-svt, av1-qsv, av1-nvenc, av1-vaapi, vp9-*, hevc-*)
//! - Hardware test profiles (for validation and testing)
//! - User-friendly named profiles (4K Film, 1080p Shrinker, etc.)

use super::av1_config::{Av1Config, Codec};
use super::profile::Profile;
use super::vp9_config::Vp9Config;

impl Profile {
    /// Get built-in profile by internal name.
    ///
    /// These are the base profiles used for encoding. For user-friendly named
    /// profiles, use `get_builtin()` instead.
    pub fn get(name: &str) -> Self {
        match name {
            "av1-svt" => Self::av1_svt(),
            "av1-qsv" => Self::av1_qsv(),
            "av1-nvenc" => Self::av1_nvenc(),
            "av1-vaapi" => Self::av1_vaapi(),
            "vp9-good" => Self::vp9_good(),
            "vp9-best" => Self::vp9_best(),
            _ => Self::vp9_good(), // default
        }
    }

    /// List built-in profile names (user-friendly display names)
    pub fn builtin_names() -> Vec<String> {
        vec![
            "1080p Shrinker".to_string(),
            "Daily Driver".to_string(),
            "Efficient 4K".to_string(),
            "1080p Film".to_string(),
            "4K Film".to_string(),
        ]
    }

    /// Get built-in profile by user-friendly name
    pub fn get_builtin(name: &str) -> Option<Self> {
        match name {
            "1080p Shrinker" => Some(Self::profile_1080p_shrinker()),
            "Daily Driver" => Some(Self::profile_daily_driver()),
            "Efficient 4K" => Some(Self::profile_efficient_4k()),
            "1080p Film" => Some(Self::profile_1080p_film()),
            "4K Film" => Some(Self::profile_4k_film()),
            _ => None,
        }
    }
}

// ============================================================================
// Helper: Common additional_args for containers
// ============================================================================

/// Additional args for MKV container (full stream preservation)
fn mkv_additional_args() -> String {
    "-map 0:s? -map 0:t? -c:s copy -c:t copy -map_metadata 0 -map_chapters 0".to_string()
}

/// Additional args for MP4 container (subtitles as mov_text, no attachments)
fn mp4_additional_args() -> String {
    "-map_metadata 0 -map_chapters 0".to_string()
}

/// Additional args for WebM container (limited - no subtitle/attachment support)
fn webm_additional_args() -> String {
    "-map_metadata 0 -map_chapters 0".to_string()
}

// ============================================================================
// Base Codec Profiles
// ============================================================================

impl Profile {
    fn av1_svt() -> Self {
        Self {
            name: "av1-svt".to_string(),
            suffix: "av1svt".to_string(),
            container: "mkv".to_string(),
            video_codec: "libsvtav1".to_string(),
            audio_primary_codec: "libopus".to_string(),
            audio_primary_bitrate: 128,
            audio_primary_downmix: false,
            audio_add_ac3: false,
            audio_ac3_bitrate: 448,
            audio_add_stereo: false,
            audio_stereo_codec: "aac".to_string(),
            audio_stereo_bitrate: 128,
            audio_codec: None,
            audio_bitrate: None,
            downmix_stereo: None,
            audio_passthrough: None,
            output_dir: ".".to_string(),
            filename_pattern: "{basename}".to_string(),
            overwrite: false,
            additional_args: mkv_additional_args(),
            fps: 0,
            scale_width: -2,
            scale_height: -2,
            crf: 28,
            video_target_bitrate: 0,
            video_min_bitrate: 0,
            video_max_bitrate: 0,
            video_bufsize: 0,
            undershoot_pct: -1,
            overshoot_pct: -1,
            cpu_used: 0,
            cpu_used_pass1: 0,
            cpu_used_pass2: 0,
            two_pass: false,
            quality_mode: "good".to_string(),
            vp9_profile: 0,
            pix_fmt: "yuv420p10le".to_string(),
            row_mt: false,
            tile_columns: 0,
            tile_rows: 0,
            threads: 0,
            frame_parallel: false,
            max_workers: 1,
            gop_length: "240".to_string(),
            keyint_min: "0".to_string(),
            fixed_gop: false,
            lag_in_frames: 0,
            auto_alt_ref: 0,
            arnr_max_frames: 0,
            arnr_strength: 0,
            arnr_type: -1,
            enable_tpl: false,
            sharpness: -1,
            noise_sensitivity: 0,
            static_thresh: "0".to_string(),
            max_intra_rate: "0".to_string(),
            aq_mode: 1,
            tune_content: "default".to_string(),
            colorspace: -1,
            color_primaries: -1,
            color_trc: -1,
            color_range: -1,
            use_hardware_encoding: false,
            hw_rc_mode: 1,
            hw_global_quality: 70,
            hw_b_frames: 0,
            hw_loop_filter_level: 16,
            hw_loop_filter_sharpness: 4,
            hw_compression_level: 4,
            codec: Codec::Av1(Av1Config {
                preset: 8,
                tune: 0,
                film_grain: 0,
                film_grain_denoise: false,
                enable_overlays: false,
                scd: true,
                scm: 2,
                enable_tf: true,
                hw_preset: "1".to_string(),
                hw_cq: 70,
                svt_crf: 28,
                qsv_cq: 70,
                nvenc_cq: 28,
                vaapi_cq: 70,
                hw_lookahead: 0,
                hw_tile_cols: 0,
                hw_tile_rows: 0,
                hw_denoise: 0,
                hw_detail: 0,
            }),
            vmaf_enabled: false,
            vmaf_target: 93.0,
            vmaf_window_duration_sec: 10,
            vmaf_analysis_budget_sec: 60,
            vmaf_n_subsample: 30,
            vmaf_max_attempts: 3,
            vmaf_step: 2,
        }
    }

    fn av1_qsv() -> Self {
        Self {
            name: "av1-qsv".to_string(),
            suffix: "av1qsv".to_string(),
            container: "mkv".to_string(),
            video_codec: "av1_qsv".to_string(),
            audio_primary_codec: "libopus".to_string(),
            audio_primary_bitrate: 128,
            audio_primary_downmix: false,
            audio_add_ac3: false,
            audio_ac3_bitrate: 448,
            audio_add_stereo: false,
            audio_stereo_codec: "aac".to_string(),
            audio_stereo_bitrate: 128,
            audio_codec: None,
            audio_bitrate: None,
            downmix_stereo: None,
            audio_passthrough: None,
            output_dir: ".".to_string(),
            filename_pattern: "{basename}".to_string(),
            overwrite: false,
            additional_args: mkv_additional_args(),
            fps: 0,
            scale_width: -2,
            scale_height: -2,
            crf: 0,
            video_target_bitrate: 0,
            video_min_bitrate: 0,
            video_max_bitrate: 0,
            video_bufsize: 0,
            undershoot_pct: -1,
            overshoot_pct: -1,
            cpu_used: 0,
            cpu_used_pass1: 0,
            cpu_used_pass2: 0,
            two_pass: false,
            quality_mode: "good".to_string(),
            vp9_profile: 0,
            pix_fmt: "auto".to_string(),
            row_mt: false,
            tile_columns: 0,
            tile_rows: 0,
            threads: 0,
            frame_parallel: false,
            max_workers: 1,
            gop_length: "240".to_string(),
            keyint_min: "0".to_string(),
            fixed_gop: false,
            lag_in_frames: 0,
            auto_alt_ref: 0,
            arnr_max_frames: 0,
            arnr_strength: 0,
            arnr_type: -1,
            enable_tpl: false,
            sharpness: -1,
            noise_sensitivity: 0,
            static_thresh: "0".to_string(),
            max_intra_rate: "0".to_string(),
            aq_mode: 1,
            tune_content: "default".to_string(),
            colorspace: -1,
            color_primaries: -1,
            color_trc: -1,
            color_range: -1,
            use_hardware_encoding: true,
            hw_rc_mode: 1,
            hw_global_quality: 70,
            hw_b_frames: 0,
            hw_loop_filter_level: 16,
            hw_loop_filter_sharpness: 4,
            hw_compression_level: 4,
            codec: Codec::Av1(Av1Config {
                preset: 8,
                tune: 0,
                film_grain: 0,
                film_grain_denoise: false,
                enable_overlays: false,
                scd: true,
                scm: 2,
                enable_tf: true,
                hw_preset: "1".to_string(),
                hw_cq: 70,
                svt_crf: 28,
                qsv_cq: 70,
                nvenc_cq: 28,
                vaapi_cq: 70,
                hw_lookahead: 40,
                hw_tile_cols: 0,
                hw_tile_rows: 0,
                hw_denoise: 0,
                hw_detail: 0,
            }),
            vmaf_enabled: false,
            vmaf_target: 93.0,
            vmaf_window_duration_sec: 10,
            vmaf_analysis_budget_sec: 60,
            vmaf_n_subsample: 30,
            vmaf_max_attempts: 3,
            vmaf_step: 2,
        }
    }

    fn av1_nvenc() -> Self {
        Self {
            name: "av1-nvenc".to_string(),
            suffix: "av1nvenc".to_string(),
            container: "mkv".to_string(),
            video_codec: "av1_nvenc".to_string(),
            audio_primary_codec: "libopus".to_string(),
            audio_primary_bitrate: 128,
            audio_primary_downmix: false,
            audio_add_ac3: false,
            audio_ac3_bitrate: 448,
            audio_add_stereo: false,
            audio_stereo_codec: "aac".to_string(),
            audio_stereo_bitrate: 128,
            audio_codec: None,
            audio_bitrate: None,
            downmix_stereo: None,
            audio_passthrough: None,
            output_dir: ".".to_string(),
            filename_pattern: "{basename}".to_string(),
            overwrite: false,
            additional_args: mkv_additional_args(),
            fps: 0,
            scale_width: -2,
            scale_height: -2,
            crf: 0,
            video_target_bitrate: 0,
            video_min_bitrate: 0,
            video_max_bitrate: 0,
            video_bufsize: 0,
            undershoot_pct: -1,
            overshoot_pct: -1,
            cpu_used: 0,
            cpu_used_pass1: 0,
            cpu_used_pass2: 0,
            two_pass: false,
            quality_mode: "good".to_string(),
            vp9_profile: 0,
            pix_fmt: "auto".to_string(),
            row_mt: false,
            tile_columns: 0,
            tile_rows: 0,
            threads: 0,
            frame_parallel: false,
            max_workers: 1,
            gop_length: "240".to_string(),
            keyint_min: "0".to_string(),
            fixed_gop: false,
            lag_in_frames: 0,
            auto_alt_ref: 0,
            arnr_max_frames: 0,
            arnr_strength: 0,
            arnr_type: -1,
            enable_tpl: false,
            sharpness: -1,
            noise_sensitivity: 0,
            static_thresh: "0".to_string(),
            max_intra_rate: "0".to_string(),
            aq_mode: 1,
            tune_content: "default".to_string(),
            colorspace: -1,
            color_primaries: -1,
            color_trc: -1,
            color_range: -1,
            use_hardware_encoding: true,
            hw_rc_mode: 1,
            hw_global_quality: 70,
            hw_b_frames: 0,
            hw_loop_filter_level: 16,
            hw_loop_filter_sharpness: 4,
            hw_compression_level: 4,
            codec: Codec::Av1(Av1Config {
                preset: 8,
                tune: 0,
                film_grain: 0,
                film_grain_denoise: false,
                enable_overlays: false,
                scd: true,
                scm: 2,
                enable_tf: true,
                hw_preset: "p4".to_string(),
                hw_cq: 28,
                svt_crf: 28,
                qsv_cq: 70,
                nvenc_cq: 28,
                vaapi_cq: 70,
                hw_lookahead: 0,
                hw_tile_cols: 0,
                hw_tile_rows: 0,
                hw_denoise: 0,
                hw_detail: 0,
            }),
            vmaf_enabled: false,
            vmaf_target: 93.0,
            vmaf_window_duration_sec: 10,
            vmaf_analysis_budget_sec: 60,
            vmaf_n_subsample: 30,
            vmaf_max_attempts: 3,
            vmaf_step: 2,
        }
    }

    fn av1_vaapi() -> Self {
        Self {
            name: "av1-vaapi".to_string(),
            suffix: "av1vaapi".to_string(),
            container: "mkv".to_string(),
            video_codec: "av1_vaapi".to_string(),
            audio_primary_codec: "libopus".to_string(),
            audio_primary_bitrate: 128,
            audio_primary_downmix: false,
            audio_add_ac3: false,
            audio_ac3_bitrate: 448,
            audio_add_stereo: false,
            audio_stereo_codec: "aac".to_string(),
            audio_stereo_bitrate: 128,
            audio_codec: None,
            audio_bitrate: None,
            downmix_stereo: None,
            audio_passthrough: None,
            output_dir: ".".to_string(),
            filename_pattern: "{basename}".to_string(),
            overwrite: false,
            additional_args: mkv_additional_args(),
            fps: 0,
            scale_width: -2,
            scale_height: -2,
            crf: 0,
            video_target_bitrate: 0,
            video_min_bitrate: 0,
            video_max_bitrate: 0,
            video_bufsize: 0,
            undershoot_pct: -1,
            overshoot_pct: -1,
            cpu_used: 0,
            cpu_used_pass1: 0,
            cpu_used_pass2: 0,
            two_pass: false,
            quality_mode: "good".to_string(),
            vp9_profile: 0,
            pix_fmt: "auto".to_string(),
            row_mt: false,
            tile_columns: 0,
            tile_rows: 0,
            threads: 0,
            frame_parallel: false,
            max_workers: 1,
            gop_length: "240".to_string(),
            keyint_min: "0".to_string(),
            fixed_gop: false,
            lag_in_frames: 0,
            auto_alt_ref: 0,
            arnr_max_frames: 0,
            arnr_strength: 0,
            arnr_type: -1,
            enable_tpl: false,
            sharpness: -1,
            noise_sensitivity: 0,
            static_thresh: "0".to_string(),
            max_intra_rate: "0".to_string(),
            aq_mode: 1,
            tune_content: "default".to_string(),
            colorspace: -1,
            color_primaries: -1,
            color_trc: -1,
            color_range: -1,
            use_hardware_encoding: true,
            hw_rc_mode: 1,
            hw_global_quality: 70,
            hw_b_frames: 0,
            hw_loop_filter_level: 16,
            hw_loop_filter_sharpness: 4,
            hw_compression_level: 4,
            codec: Codec::Av1(Av1Config {
                preset: 8,
                tune: 0,
                film_grain: 0,
                film_grain_denoise: false,
                enable_overlays: false,
                scd: true,
                scm: 2,
                enable_tf: true,
                hw_preset: "1".to_string(),
                hw_cq: 70,
                svt_crf: 28,
                qsv_cq: 70,
                nvenc_cq: 28,
                vaapi_cq: 70,
                hw_lookahead: 0,
                hw_tile_cols: 0,
                hw_tile_rows: 0,
                hw_denoise: 0,
                hw_detail: 0,
            }),
            vmaf_enabled: false,
            vmaf_target: 93.0,
            vmaf_window_duration_sec: 10,
            vmaf_analysis_budget_sec: 60,
            vmaf_n_subsample: 30,
            vmaf_max_attempts: 3,
            vmaf_step: 2,
        }
    }
}

// ============================================================================
// VP9 Profiles
// ============================================================================

impl Profile {
    fn vp9_good() -> Self {
        Self {
            name: "vp9-good".to_string(),
            suffix: "vp9good".to_string(),
            container: "webm".to_string(),
            video_codec: "libvpx-vp9".to_string(),
            audio_primary_codec: "libopus".to_string(),
            audio_primary_bitrate: 128,
            audio_primary_downmix: false,
            audio_add_ac3: false,
            audio_ac3_bitrate: 448,
            audio_add_stereo: false,
            audio_stereo_codec: "aac".to_string(),
            audio_stereo_bitrate: 128,
            audio_codec: None,
            audio_bitrate: None,
            downmix_stereo: None,
            audio_passthrough: None,
            output_dir: ".".to_string(),
            filename_pattern: "{basename}".to_string(),
            overwrite: false,
            additional_args: webm_additional_args(),
            fps: 0,
            scale_width: -2,
            scale_height: -2,
            crf: 30,
            video_target_bitrate: 0,
            video_min_bitrate: 0,
            video_max_bitrate: 0,
            video_bufsize: 0,
            undershoot_pct: -1,
            overshoot_pct: -1,
            cpu_used: 1,
            cpu_used_pass1: 4,
            cpu_used_pass2: 1,
            two_pass: false,
            quality_mode: "good".to_string(),
            vp9_profile: 0,
            pix_fmt: "auto".to_string(),
            row_mt: true,
            tile_columns: 2,
            tile_rows: 0,
            threads: 0,
            frame_parallel: false,
            max_workers: 1,
            gop_length: "240".to_string(),
            keyint_min: "0".to_string(),
            fixed_gop: false,
            lag_in_frames: 25,
            auto_alt_ref: 1,
            arnr_max_frames: 7,
            arnr_strength: 4,
            arnr_type: 3,
            enable_tpl: true,
            sharpness: -1,
            noise_sensitivity: 0,
            static_thresh: "0".to_string(),
            max_intra_rate: "0".to_string(),
            aq_mode: 0,
            tune_content: "default".to_string(),
            colorspace: -1,
            color_primaries: -1,
            color_trc: -1,
            color_range: -1,
            use_hardware_encoding: false,
            hw_rc_mode: 1,
            hw_global_quality: 70,
            hw_b_frames: 0,
            hw_loop_filter_level: 16,
            hw_loop_filter_sharpness: 4,
            hw_compression_level: 4,
            codec: Codec::Vp9(Vp9Config::default()),
            vmaf_enabled: false,
            vmaf_target: 93.0,
            vmaf_window_duration_sec: 10,
            vmaf_analysis_budget_sec: 60,
            vmaf_n_subsample: 30,
            vmaf_max_attempts: 3,
            vmaf_step: 2,
        }
    }

    fn vp9_best() -> Self {
        Self {
            name: "vp9-best".to_string(),
            suffix: "vp9best".to_string(),
            cpu_used: 0,
            cpu_used_pass1: 4,
            cpu_used_pass2: 0,
            quality_mode: "best".to_string(),
            lag_in_frames: 25,
            ..Self::vp9_good()
        }
    }

}

// ============================================================================
// User-Friendly Named Profiles
// ============================================================================

impl Profile {
    /// 1080p Shrinker: Maximum compression for space savings
    /// MP4, AAC 112k, AV1, CRF 43, 8-bit SDR, 1080p
    fn profile_1080p_shrinker() -> Self {
        Self {
            name: "1080p Shrinker".to_string(),
            suffix: "1080p_shrinker".to_string(),
            container: "mp4".to_string(),
            video_codec: "libsvtav1".to_string(),
            audio_primary_codec: "aac".to_string(),
            audio_primary_bitrate: 112,
            audio_primary_downmix: false,
            audio_add_ac3: false,
            audio_ac3_bitrate: 448,
            audio_add_stereo: false,
            audio_stereo_codec: "aac".to_string(),
            audio_stereo_bitrate: 128,
            audio_codec: None,
            audio_bitrate: None,
            downmix_stereo: None,
            audio_passthrough: None,
            output_dir: ".".to_string(),
            filename_pattern: "{basename}".to_string(),
            overwrite: false,
            additional_args: mp4_additional_args(),
            fps: 30,
            scale_width: 1920,
            scale_height: 1080,
            crf: 43,
            video_target_bitrate: 0,
            video_min_bitrate: 0,
            video_max_bitrate: 0,
            video_bufsize: 0,
            undershoot_pct: -1,
            overshoot_pct: -1,
            cpu_used: 0,
            cpu_used_pass1: 0,
            cpu_used_pass2: 0,
            two_pass: false,
            quality_mode: "good".to_string(),
            vp9_profile: 0,
            pix_fmt: "yuv420p".to_string(), // 8-bit SDR
            row_mt: false,
            tile_columns: 0,
            tile_rows: 0,
            threads: 0,
            frame_parallel: false,
            max_workers: 1,
            gop_length: "240".to_string(),
            keyint_min: "0".to_string(),
            fixed_gop: false,
            lag_in_frames: 0,
            auto_alt_ref: 0,
            arnr_max_frames: 0,
            arnr_strength: 0,
            arnr_type: -1,
            enable_tpl: false,
            sharpness: -1,
            noise_sensitivity: 0,
            static_thresh: "0".to_string(),
            max_intra_rate: "0".to_string(),
            aq_mode: 1,
            tune_content: "default".to_string(),
            // Force SDR (BT.709)
            colorspace: 1,
            color_primaries: 1,
            color_trc: 1,
            color_range: -1,
            use_hardware_encoding: false,
            hw_rc_mode: 1,
            hw_global_quality: 70,
            hw_b_frames: 0,
            hw_loop_filter_level: 16,
            hw_loop_filter_sharpness: 4,
            hw_compression_level: 4,
            codec: Codec::Av1(Av1Config {
                preset: 8,
                tune: 0,
                film_grain: 0,
                film_grain_denoise: false,
                enable_overlays: false,
                scd: true,
                scm: 2,
                enable_tf: true,
                hw_preset: "1".to_string(),
                hw_cq: 125,
                svt_crf: 43,
                qsv_cq: 125,
                nvenc_cq: 43,
                vaapi_cq: 125,
                hw_lookahead: 0,
                hw_tile_cols: 0,
                hw_tile_rows: 0,
                hw_denoise: 0,
                hw_detail: 0,
            }),
            vmaf_enabled: false,
            vmaf_target: 93.0,
            vmaf_window_duration_sec: 10,
            vmaf_analysis_budget_sec: 60,
            vmaf_n_subsample: 30,
            vmaf_max_attempts: 3,
            vmaf_step: 2,
        }
    }

    /// Daily Driver: Compact 720p for everyday use
    /// MP4, AAC 96k stereo, AV1, CRF 45, 720p 30fps
    fn profile_daily_driver() -> Self {
        Self {
            name: "Daily Driver".to_string(),
            suffix: "daily".to_string(),
            container: "mp4".to_string(),
            video_codec: "libsvtav1".to_string(),
            audio_primary_codec: "aac".to_string(),
            audio_primary_bitrate: 96,
            audio_primary_downmix: true, // Downmix to stereo
            audio_add_ac3: false,
            audio_ac3_bitrate: 448,
            audio_add_stereo: false,
            audio_stereo_codec: "aac".to_string(),
            audio_stereo_bitrate: 128,
            audio_codec: None,
            audio_bitrate: None,
            downmix_stereo: None,
            audio_passthrough: None,
            output_dir: ".".to_string(),
            filename_pattern: "{basename}".to_string(),
            overwrite: false,
            additional_args: mp4_additional_args(),
            fps: 30,
            scale_width: 1280,
            scale_height: 720,
            crf: 45,
            video_target_bitrate: 0,
            video_min_bitrate: 0,
            video_max_bitrate: 0,
            video_bufsize: 0,
            undershoot_pct: -1,
            overshoot_pct: -1,
            cpu_used: 0,
            cpu_used_pass1: 0,
            cpu_used_pass2: 0,
            two_pass: false,
            quality_mode: "good".to_string(),
            vp9_profile: 0,
            pix_fmt: "yuv420p".to_string(), // 8-bit for compatibility
            row_mt: false,
            tile_columns: 0,
            tile_rows: 0,
            threads: 0,
            frame_parallel: false,
            max_workers: 1,
            gop_length: "240".to_string(),
            keyint_min: "0".to_string(),
            fixed_gop: false,
            lag_in_frames: 0,
            auto_alt_ref: 0,
            arnr_max_frames: 0,
            arnr_strength: 0,
            arnr_type: -1,
            enable_tpl: false,
            sharpness: -1,
            noise_sensitivity: 0,
            static_thresh: "0".to_string(),
            max_intra_rate: "0".to_string(),
            aq_mode: 1,
            tune_content: "default".to_string(),
            // Force SDR (BT.709)
            colorspace: 1,
            color_primaries: 1,
            color_trc: 1,
            color_range: -1,
            use_hardware_encoding: false,
            hw_rc_mode: 1,
            hw_global_quality: 70,
            hw_b_frames: 0,
            hw_loop_filter_level: 16,
            hw_loop_filter_sharpness: 4,
            hw_compression_level: 4,
            codec: Codec::Av1(Av1Config {
                preset: 8,
                tune: 0,
                film_grain: 0,
                film_grain_denoise: false,
                enable_overlays: false,
                scd: true,
                scm: 2,
                enable_tf: true,
                hw_preset: "1".to_string(),
                hw_cq: 130,
                svt_crf: 45,
                qsv_cq: 130,
                nvenc_cq: 45,
                vaapi_cq: 130,
                hw_lookahead: 0,
                hw_tile_cols: 0,
                hw_tile_rows: 0,
                hw_denoise: 0,
                hw_detail: 0,
            }),
            vmaf_enabled: false,
            vmaf_target: 93.0,
            vmaf_window_duration_sec: 10,
            vmaf_analysis_budget_sec: 60,
            vmaf_n_subsample: 30,
            vmaf_max_attempts: 3,
            vmaf_step: 2,
        }
    }

    /// Efficient 4K: Fast hardware encoding for 4K content
    /// MP4, Opus 128k, QSV AV1, CQ 125, 4K 30fps
    fn profile_efficient_4k() -> Self {
        Self {
            name: "Efficient 4K".to_string(),
            suffix: "efficient_4k".to_string(),
            container: "mp4".to_string(),
            video_codec: "av1_qsv".to_string(),
            audio_primary_codec: "libopus".to_string(),
            audio_primary_bitrate: 128,
            audio_primary_downmix: false,
            audio_add_ac3: false,
            audio_ac3_bitrate: 448,
            audio_add_stereo: false,
            audio_stereo_codec: "aac".to_string(),
            audio_stereo_bitrate: 128,
            audio_codec: None,
            audio_bitrate: None,
            downmix_stereo: None,
            audio_passthrough: None,
            output_dir: ".".to_string(),
            filename_pattern: "{basename}".to_string(),
            overwrite: false,
            additional_args: mp4_additional_args(),
            fps: 30,
            scale_width: 3840,
            scale_height: 2160,
            crf: 0,
            video_target_bitrate: 0,
            video_min_bitrate: 0,
            video_max_bitrate: 0,
            video_bufsize: 0,
            undershoot_pct: -1,
            overshoot_pct: -1,
            cpu_used: 0,
            cpu_used_pass1: 0,
            cpu_used_pass2: 0,
            two_pass: false,
            quality_mode: "good".to_string(),
            vp9_profile: 0,
            pix_fmt: "auto".to_string(),
            row_mt: false,
            tile_columns: 0,
            tile_rows: 0,
            threads: 0,
            frame_parallel: false,
            max_workers: 1,
            gop_length: "240".to_string(),
            keyint_min: "0".to_string(),
            fixed_gop: false,
            lag_in_frames: 0, // Not used for QSV - hw_lookahead is used instead
            auto_alt_ref: 0,
            arnr_max_frames: 0,
            arnr_strength: 0,
            arnr_type: -1,
            enable_tpl: false,
            sharpness: -1,
            noise_sensitivity: 0,
            static_thresh: "0".to_string(),
            max_intra_rate: "0".to_string(),
            aq_mode: 1,
            tune_content: "default".to_string(),
            colorspace: -1,
            color_primaries: -1,
            color_trc: -1,
            color_range: -1,
            use_hardware_encoding: true,
            hw_rc_mode: 1,
            hw_global_quality: 125,
            hw_b_frames: 0,
            hw_loop_filter_level: 16,
            hw_loop_filter_sharpness: 4,
            hw_compression_level: 4,
            codec: Codec::Av1(Av1Config {
                preset: 6,
                tune: 0,
                film_grain: 0,
                film_grain_denoise: false,
                enable_overlays: false,
                scd: true,
                scm: 2,
                enable_tf: true,
                hw_preset: "1".to_string(),
                hw_cq: 125,
                svt_crf: 35,
                qsv_cq: 125,
                nvenc_cq: 35,
                vaapi_cq: 125,
                hw_lookahead: 40,
                hw_tile_cols: 2,
                hw_tile_rows: 2,
                hw_denoise: 0,
                hw_detail: 30,
            }),
            vmaf_enabled: false,
            vmaf_target: 93.0,
            vmaf_window_duration_sec: 10,
            vmaf_analysis_budget_sec: 60,
            vmaf_n_subsample: 30,
            vmaf_max_attempts: 3,
            vmaf_step: 2,
        }
    }

    /// 1080p Film: High-quality archival at 1080p
    /// MKV, passthrough + AC3, QSV AV1, 1080p
    fn profile_1080p_film() -> Self {
        Self {
            name: "1080p Film".to_string(),
            suffix: "1080p_film".to_string(),
            container: "mkv".to_string(),
            video_codec: "av1_qsv".to_string(),
            audio_primary_codec: "passthrough".to_string(),
            audio_primary_bitrate: 0,
            audio_primary_downmix: false,
            audio_add_ac3: true,
            audio_ac3_bitrate: 448,
            audio_add_stereo: false,
            audio_stereo_codec: "aac".to_string(),
            audio_stereo_bitrate: 128,
            audio_codec: None,
            audio_bitrate: None,
            downmix_stereo: None,
            audio_passthrough: None,
            output_dir: ".".to_string(),
            filename_pattern: "{basename}".to_string(),
            overwrite: false,
            additional_args: mkv_additional_args(),
            fps: 0,
            scale_width: 1920,
            scale_height: 1080,
            crf: 21,
            video_target_bitrate: 0,
            video_min_bitrate: 0,
            video_max_bitrate: 0,
            video_bufsize: 0,
            undershoot_pct: -1,
            overshoot_pct: -1,
            cpu_used: 0,
            cpu_used_pass1: 0,
            cpu_used_pass2: 0,
            two_pass: false,
            quality_mode: "good".to_string(),
            vp9_profile: 0,
            pix_fmt: "auto".to_string(),
            row_mt: false,
            tile_columns: 0,
            tile_rows: 0,
            threads: 0,
            frame_parallel: false,
            max_workers: 1,
            gop_length: "240".to_string(),
            keyint_min: "0".to_string(),
            fixed_gop: false,
            lag_in_frames: 0, // Not used for QSV - hw_lookahead is used instead
            auto_alt_ref: 0,
            arnr_max_frames: 0,
            arnr_strength: 0,
            arnr_type: -1,
            enable_tpl: false,
            sharpness: -1,
            noise_sensitivity: 0,
            static_thresh: "0".to_string(),
            max_intra_rate: "0".to_string(),
            aq_mode: 1,
            tune_content: "default".to_string(),
            colorspace: -1,
            color_primaries: -1,
            color_trc: -1,
            color_range: -1,
            use_hardware_encoding: true,
            hw_rc_mode: 1,
            hw_global_quality: 85,
            hw_b_frames: 0,
            hw_loop_filter_level: 16,
            hw_loop_filter_sharpness: 4,
            hw_compression_level: 4,
            codec: Codec::Av1(Av1Config {
                preset: 6,
                tune: 0,
                film_grain: 0,
                film_grain_denoise: false,
                enable_overlays: false,
                scd: true,
                scm: 2,
                enable_tf: true,
                hw_preset: "1".to_string(),
                hw_cq: 85,
                svt_crf: 21,
                qsv_cq: 85,
                nvenc_cq: 21,
                vaapi_cq: 85,
                hw_lookahead: 40,
                hw_tile_cols: 1,
                hw_tile_rows: 1,
                hw_denoise: 0,
                hw_detail: 0,
            }),
            vmaf_enabled: false,
            vmaf_target: 93.0,
            vmaf_window_duration_sec: 10,
            vmaf_analysis_budget_sec: 60,
            vmaf_n_subsample: 30,
            vmaf_max_attempts: 3,
            vmaf_step: 2,
        }
    }

    /// 4K Film: High-quality archival for 4K HDR content
    /// MKV, passthrough + AC3, QSV AV1, native resolution
    fn profile_4k_film() -> Self {
        Self {
            name: "4K Film".to_string(),
            suffix: "4k_film".to_string(),
            container: "mkv".to_string(),
            video_codec: "av1_qsv".to_string(),
            audio_primary_codec: "passthrough".to_string(),
            audio_primary_bitrate: 0,
            audio_primary_downmix: false,
            audio_add_ac3: true,
            audio_ac3_bitrate: 448,
            audio_add_stereo: false,
            audio_stereo_codec: "aac".to_string(),
            audio_stereo_bitrate: 128,
            audio_codec: None,
            audio_bitrate: None,
            downmix_stereo: None,
            audio_passthrough: None,
            output_dir: ".".to_string(),
            filename_pattern: "{basename}".to_string(),
            overwrite: false,
            additional_args: mkv_additional_args(),
            fps: 0,
            scale_width: -2,
            scale_height: -2,
            crf: 21,
            video_target_bitrate: 0,
            video_min_bitrate: 0,
            video_max_bitrate: 0,
            video_bufsize: 0,
            undershoot_pct: -1,
            overshoot_pct: -1,
            cpu_used: 0,
            cpu_used_pass1: 0,
            cpu_used_pass2: 0,
            two_pass: false,
            quality_mode: "good".to_string(),
            vp9_profile: 0,
            pix_fmt: "auto".to_string(),
            row_mt: false,
            tile_columns: 0,
            tile_rows: 0,
            threads: 0,
            frame_parallel: false,
            max_workers: 1,
            gop_length: "240".to_string(),
            keyint_min: "0".to_string(),
            fixed_gop: false,
            lag_in_frames: 0, // Not used for QSV - hw_lookahead is used instead
            auto_alt_ref: 0,
            arnr_max_frames: 0,
            arnr_strength: 0,
            arnr_type: -1,
            enable_tpl: false,
            sharpness: -1,
            noise_sensitivity: 0,
            static_thresh: "0".to_string(),
            max_intra_rate: "0".to_string(),
            aq_mode: 1,
            tune_content: "default".to_string(),
            colorspace: -1,
            color_primaries: -1,
            color_trc: -1,
            color_range: -1,
            use_hardware_encoding: true,
            hw_rc_mode: 1,
            hw_global_quality: 85,
            hw_b_frames: 0,
            hw_loop_filter_level: 16,
            hw_loop_filter_sharpness: 4,
            hw_compression_level: 4,
            codec: Codec::Av1(Av1Config {
                preset: 6,
                tune: 0,
                film_grain: 0,
                film_grain_denoise: false,
                enable_overlays: false,
                scd: true,
                scm: 2,
                enable_tf: true,
                hw_preset: "1".to_string(),
                hw_cq: 85,
                svt_crf: 21,
                qsv_cq: 85,
                nvenc_cq: 21,
                vaapi_cq: 85,
                hw_lookahead: 40,
                hw_tile_cols: 1,
                hw_tile_rows: 1,
                hw_denoise: 0,
                hw_detail: 0,
            }),
            vmaf_enabled: false,
            vmaf_target: 93.0,
            vmaf_window_duration_sec: 10,
            vmaf_analysis_budget_sec: 60,
            vmaf_n_subsample: 30,
            vmaf_max_attempts: 3,
            vmaf_step: 2,
        }
    }
}
